sonar.organization=chunglong-chen
sonar.projectKey=chunglong-chen_gpa7650
sonar.projectName=gpa7650
sonar.sources=psc700-gpa7650
sonar.cfamily.compile-commands=compile_commands.json
# Tells Sonar to ignore missing vendor include files so the scan doesn't abort
sonar.cfamily.skipUnsupportedCompilers=true
